### ISSUE TITLE
🐛 Bug Report: Chrome console error when uploading company logo

### ISSUE THREAD

**Issue by shanehughes1990** [novuhq/novu#1242]
### 📜 Description

When attempting to upload a company logo, after selecting what image you want to add and pressing open, nothing happens visually. Upon inspecting the chrome console logs I am getting a couple of errors.

We originally thought it was the proxy buffer size on nginx ingress in front of these services, we increased it from the default 1m to 1g (just so we could rule out any picture size issues with the reverse proxy itself). The same errors happen after we did that.

So without having any of the S3 variables filled out I have to presume that the picture is assumed to be stored as an s3 object, I could not find any documentation of the sorts.

### 👟 Reproduction steps

1. Setup a self hosted instance of the novu apps (I don't have any of the s3 env variables filled out)
3. Open browser console
2. Go to web frontend
4. Go to "Settings"
5. Press the upload image button
6. Select an image to upload
7. Press Okay (windows)
8. View console logs for error

### 👍 Expected behavior

It should upload the image to "Your Logo" in settings

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/31993465/188946896-c5d6a36c-2ec1-43fe-9e81-b0f7ead11bd8.png)

### 💻 Operating system

Linux

### 🤖 Node Version

whatever is on novuhq container 0.7.3

### 📃 Provide any additional context for the Bug.

Docker env settings
```
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: API_ROOT_URL
          value: https://OBFUSCATED
        - name: PORT
          value: "3000"
        - name: FRONT_BASE_URL
          value: https://OBFUSCATED
        - name: REDIS_HOST
          value: redis.default.svc
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB_INDEX
          value: "2"
        - name: DISABLE_USER_REGISTRATION
          value: "true"
        - name: SECRET_CHANGE
          value: e041fe1d3335bbcde5aa00ac3a4b38b604ca192c
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: api
              optional: false
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              key: MONGO_URL
              name: api
              optional: false
        image: ghcr.io/novuhq/novu/api:0.7.3
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 3000
          name: app-port
          protocol: TCP
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)
