### ISSUE TITLE
[NV-2435] Feature: Create feature flag for IN_MEMORY_CLUSTER_MODE_ENABLED in Launch Darkly

### ISSUE THREAD

**Issue by marceloaguero** [novuhq/novu#3594]
- **I'm submitting a...**
   - [*] bug report
   - [ ] feature request
   - [ ] question about the decisions made in the repository
   - [*] question about how to use this project

- **Summary**

I'm trying to run novu from the manifests that kustomize generates.

The steps I followed, after cloning the repository, are the following:
```
 cd docker/kubernetes/kustomize
```

Edit env-dev leaving the content attached.

Generate the manifests for kubernetes:
```
 customize build . > novu.yaml
```

Create the namespace in k8s:
```
kubectl create ns novu
```

Apply the manifests:
```
kubectl apply -f novu.yaml
```

Everything worked fine except that the api and worker pods show the following error:

```
{"level":30,"time":1686759257963,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster connecting"}
{"level":50,"time":1686759257968,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","err":{"type":"ClusterAllFailedError","message":"Failed to refresh slots cache.","stack":"ClusterAllFailedError: Failed to refresh slots cache.\n    at tryNode (/usr/src/app/node_modules/.pnpm/ioredis@5.3.1/node_modules/ioredis/built/cluster/index.js:308:31)\n    at /usr/src/app/node_modules/.pnpm/ioredis@5.3.1/node_modules/ioredis/built/cluster/index.js:325:21\n    at /usr/src/app/node_modules/.pnpm/ioredis@5.3.1/node_modules/ioredis/built/cluster/index.js:662:24\n    at run (/usr/src/app/node_modules/.pnpm/ioredis@5.3.1/node_modules/ioredis/built/utils/index.js:117:22)\n    at tryCatcher (/usr/src/app/node_modules/.pnpm/standard-as-callback@2.1.0/node_modules/standard-as-callback/built/utils.js:12:23)\n    at /usr/src/app/node_modules/.pnpm/standard-as-callback@2.1.0/node_modules/standard-as-callback/built/index.js:33:51\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","lastNodeError":{"type":"Error","message":"Connection is closed.","stack":"Error: Connection is closed.\n    at close (/usr/src/app/node_modules/.pnpm/ioredis@5.3.1/node_modules/ioredis/built/redis/event_handler.js:189:25)\n    at Socket.<anonymous> (/usr/src/app/node_modules/.pnpm/ioredis@5.3.1/node_modules/ioredis/built/redis/event_handler.js:160:20)\n    at Object.onceWrapper (node:events:628:26)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at TCP.<anonymous> (node:net:301:12)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"}},"msg":"Failed to refresh slots cache."}
{"level":40,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster close"}
{"level":40,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster close"}
{"level":40,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster close"}
{"level":40,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster close"}
{"level":40,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster close"}
{"level":40,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster close"}
{"level":30,"time":1686759257972,"pid":18,"serviceName":"@novu/api","serviceVersion":"0.15.0","platform":"Docker","tenant":"OS","context":"InMemoryCluster","msg":"In-memory cluster reconnecting"}
```

Is there something I'm doing wrong?
Thanks!

- **Other information** (_e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc._)

kubernetes version: v1.26.3

env-dev:

```
# Secrets
# YOU MUST CHANGE THESE BEFORE GOING INTO PRODUCTION
JWT_SECRET=u46e2tgiacgey8tn83rc5n8htfxf406dq2oy1ys2
STORE_ENCRYPTION_KEY=DVtqBkKr88JLrhDxsfjtjiw3Pt8qMCzu

## General
NODE_ENV=dev
MONGO_URL=mongodb://novu-mongodb-dev:27017/novu-db
MONGO_MAX_POOL_SIZE=500
REDIS_HOST=novu-redis-dev
REDIS_CACHE_SERVICE_HOST=novu-redis-dev
REDIS_CACHE_SERVICE_PORT=6379

# AWS
S3_LOCAL_STACK=http://localhost:4566
S3_BUCKET_NAME=novu-local
S3_REGION=us-east-1
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test

# Ports
API_PORT=3000
REDIS_PORT=6379
WS_PORT=3002

# Root URL
REACT_APP_API_URL=http://novu-api-dev:3000
REACT_APP_WS_URL=http://novu-ws-dev:3002
API_ROOT_URL=http://novu-api-dev:3000
DISABLE_USER_REGISTRATION=false
FRONT_BASE_URL=http://novu-web-dev:4200
WIDGET_EMBED_PATH=http://novu-embed-dev:4701/embed.umd.min.js
WIDGET_URL=http://novu-widget-dev:4500

# Context Paths
# Only needed for setups with reverse-proxies
GLOBAL_CONTEXT_PATH=
WEB_CONTEXT_PATH=
API_CONTEXT_PATH=
WS_CONTEXT_PATH=
WIDGET_CONTEXT_PATH=
```

novu.yaml:

```
apiVersion: v1
data:
  API_CONTEXT_PATH: ""
  API_PORT: "3000"
  API_ROOT_URL: http://novu-api-dev:3000
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  DISABLE_USER_REGISTRATION: "false"
  FRONT_BASE_URL: http://novu-web-dev:4200
  GLOBAL_CONTEXT_PATH: ""
  JWT_SECRET: u46e2tgiacgey8tn83rc5n8htfxf406dq2oy1ys2
  MONGO_MAX_POOL_SIZE: "500"
  MONGO_URL: mongodb://novu-mongodb-dev:27017/novu-db
  NODE_ENV: dev
  REACT_APP_API_URL: http://novu-api-dev:3000
  REACT_APP_WS_URL: http://novu-ws-dev:3002
  REDIS_CACHE_SERVICE_HOST: novu-redis-dev
  REDIS_CACHE_SERVICE_PORT: "6379"
  REDIS_HOST: novu-redis-dev
  REDIS_PORT: "6379"
  S3_BUCKET_NAME: novu-local
  S3_LOCAL_STACK: http://localhost:4566
  S3_REGION: us-east-1
  STORE_ENCRYPTION_KEY: DVtqBkKr88JLrhDxsfjtjiw3Pt8qMCzu
  WEB_CONTEXT_PATH: ""
  WIDGET_CONTEXT_PATH: ""
  WIDGET_EMBED_PATH: http://novu-embed-dev:4701/embed.umd.min.js
  WIDGET_URL: http://novu-widget-dev:4500
  WS_CONTEXT_PATH: ""
  WS_PORT: "3002"
kind: ConfigMap
metadata:
  labels:
    owner: novu
  name: novu-novu-env-dev-mgdgm7kctf
  namespace: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: api
    owner: novu
  name: novu-api-dev
  namespace: novu
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app.novu.co/name: api
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: embed
    owner: novu
  name: novu-embed-dev
  namespace: novu
spec:
  ports:
  - name: "4701"
    port: 4701
    targetPort: 4701
  selector:
    app.novu.co/name: embed
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: mongodb
    owner: novu
  name: novu-mongodb-dev
  namespace: novu
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app.novu.co/name: mongodb
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: redis
    owner: novu
  name: novu-redis-dev
  namespace: novu
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.novu.co/name: redis
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: web
    owner: novu
  name: novu-web-dev
  namespace: novu
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    app.novu.co/name: web
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: widget
    owner: novu
  name: novu-widget-dev
  namespace: novu
spec:
  ports:
  - name: "4500"
    port: 4500
    targetPort: 4500
  selector:
    app.novu.co/name: widget
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: worker
    owner: novu
  name: novu-worker-dev
  namespace: novu
spec:
  ports:
  - name: "3004"
    port: 3004
    targetPort: 3004
  selector:
    app.novu.co/name: worker
    owner: novu
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: ws
    owner: novu
  name: novu-ws-dev
  namespace: novu
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 3002
  selector:
    app.novu.co/name: ws
    owner: novu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: api
    owner: novu
  name: novu-api-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: api
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: api
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: ghcr.io/novuhq/novu/api:0.15.0
        name: api
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: embed
    owner: novu
  name: novu-embed-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: embed
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: embed
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: ghcr.io/novuhq/novu/embed:0.15.0
        name: embed
        ports:
        - containerPort: 4701
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: mongodb
    owner: novu
  name: novu-mongodb-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: mongodb
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: mongodb
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: redis
    owner: novu
  name: novu-redis-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: redis
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: redis
        owner: novu
    spec:
      containers:
      - image: redis:alpine
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: web
    owner: novu
  name: novu-web-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: web
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: web
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: ghcr.io/novuhq/novu/web:0.15.0
        name: web
        ports:
        - containerPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: widget
    owner: novu
  name: novu-widget-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: widget
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: widget
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: ghcr.io/novuhq/novu/widget:0.15.0
        name: widget
        ports:
        - containerPort: 4500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: worker
    owner: novu
  name: novu-worker-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: worker
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: worker
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: ghcr.io/novuhq/novu/worker:0.15.0
        name: worker
        ports:
        - containerPort: 3004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.novu.co/name: ws
    owner: novu
  name: novu-ws-dev
  namespace: novu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.novu.co/name: ws
      owner: novu
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.novu.co/name: ws
        owner: novu
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: novu-novu-env-dev-mgdgm7kctf
        image: ghcr.io/novuhq/novu/ws:0.15.0
        name: ws
        ports:
        - containerPort: 3002
```

<sub>[NV-2435](https://linear.app/novu/issue/NV-2435/feature-create-feature-flag-for-in-memory-cluster-mode-enabled-in)</sub>
