### ISSUE TITLE
🐛 Bug Report: Getting Network Error During Signup when deployed via helm chart.

### ISSUE THREAD

**Issue by palashbasik** [novuhq/novu#4610]
### 📜 Description

I deployed novu via helm chart. I am getting network error during signup.

![image](https://github.com/novuhq/novu/assets/105476638/689e3898-9d6f-4bef-8f84-1cda98e49d0d)
![image](https://github.com/novuhq/novu/assets/105476638/20311a7d-b12e-48b5-8526-53b0e624d96f)

### 👟 Reproduction steps

I deployed the novu helm chart in K3S (Lightweight Kubernetes) v1.25.4+k3s1

1) git clone https://github.com/novuhq/novu.git
2) cd ./novu/docker/kubernetes/helm
3) Created overrides for values.yaml
values-test.yaml,
![image](https://github.com/novuhq/novu/assets/105476638/6138a0c4-9218-40fe-af9d-7d4d63e84ae7)
4) In novu/docker/kubernetes/helm/templates/web/deployment.yaml
    Replace .Values.web.env.NODE_ENV with .Values.api.env.NODE_ENV in below env
```    
env:
  - name: REACT_APP_ENVIRONMENT
    value : {{ print .Values.web.env.NODE_ENV | quote }}
```
5) My chart.yaml
```
name: novu
description: A Helm Chart for novu
version: 0.1.6
apiVersion: v2
appVersion: 0.15.0
keywords:
  - novu
  - notification framework
sources:
  - https://github.com/novuhq/novu/tree/next/docker/kubernetes/helm
home: https://novu.co/
dependencies:
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.1.6
  - condition: mongodb.enabled
    name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.0.12
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.13.3
  - condition: localstack.enabled
    name: localstack
    repository: https://localstack.github.io/helm-charts
    version: 0.6.5
``` 
Now, cd  ./novu/docker/kubernetes/helm
```
helm dependency update
helm dependency build
```
                 
6) I am using traefik for ingress. So, I added router and service for novu-web, novu-api, novu-ws.
Example: 
```    
novu-api:
  entryPoints:
    - websecure
  rule: "Host(`novu-api.xxxxxxxxxxxx`) && PathPrefix(`/`)"
  middlewares:
    - strip-service-prefix
    - corsHeader          
  tls:
    certResolver: leresolver
  service: novu-api 
  
novu-api:
  loadBalancer:
    servers:
        - url: http://novu-api.xxxxxxxxxxxx:3000
```         

Similarly, for novu-web, novu-ws.                                 

6) After configuring traefik, 
```
cd ./novu/docker/kubernetes/
helm upgrade --install novu helm  --values=./helm/values-test.yaml -n novu --create-namespace 
```
![image](https://github.com/novuhq/novu/assets/105476638/ddcb0967-d997-4e16-a78a-4e7f9ae10276)

7) In browser, hit novu-web url and try to sign up. It gives Network Error. 

@aquamanranda
@smartclash

### 👍 Expected behavior

It should let me signup.

### 👎 Actual Behavior with Screenshots

Network Error

### Novu version

0.15.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None
